version: '3.8'

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    command: ["--config.file=/etc/prometheus/prometheus.yml", "--log.level=debug"]
    volumes:
      - ./prometheus-otel-collector.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-dev
    command: ["--config=/etc/otel-collector-config.yaml", "--log-level=DEBUG"]
    volumes:
      - ./otel-collector-metrics.yml:/etc/otel-collector-config.yaml
    ports:
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "55680"       # OpenTelemetry receiver
    depends_on:
      - prometheus

  otel-agent:
    container_name: otel-agent
    image: otel/opentelemetry-collector-dev
    command: ["--config=/etc/otel-agent-config.yaml", "--log-level=DEBUG"]
    volumes:
      - ./otel-agent-metrics.yml:/etc/otel-agent-config.yaml
    ports:
      - "8887:8888"   # Prometheus metrics exposed by the agent
      - "55680"       # OpenTelemetry receiver
    depends_on:
      - otel-collector

  app:
    container_name: app
    build:
      context: .
    image: otcollector-metrics-test
    environment:
      OTEL_ENDPOINT: "otel-agent:55680"
    depends_on:
      - otel-agent