receivers:
  otlp:
    protocols:
        grpc:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: promexample
    const_labels:
      label1: value1
  logging:

processors:
  batch:
  queued_retry:

service:
  pipelines:
    traces:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging,prometheus]
